Repository canonical/gateway-api-integrator-operator, pull requests merged in 2024-07, with the labels that each got.

#38 remove build-on and run-on when arch is amd64
  .github/workflows/integration_test.yaml
  charmcraft.yaml
Labels: Libraries: Out of sync, trivial

#29 Validate gateway class in charm state
  src/charm.py
  src/resource_definition.py
  src/resource_manager/decorator.py
  src/resource_manager/gateway.py
  src/resource_manager/resource_manager.py
  src/state/config.py
  src/state/gateway.py
  src/state/tls.py
  src/state/validation.py
  tests/unit/test_certificates_integration.py
  tests/unit/test_gateway.py
Labels: Libraries: Out of sync, complex

#42 Revert the changes that cleared the charm's docs so that discourse-gatekeeper works correctly
  docs/explanation/workflow.md
  docs/index.md
  docs/reference/actions.md
  docs/reference/create_gateway_resource.png
  docs/tutorial/getting-started.md
Labels: documentation, Libraries: Out of sync, trivial

#43 enable two-way sync with discourse
  .github/workflows/promote_charm.yaml
Labels: documentation, Libraries: Out of sync, trivial

#39 Update client and state logic
  src-docs/charm.py.md
  src-docs/tls_relation.py.md
  src/charm.py
  src/resource_manager/gateway.py
  src/resource_manager/permission.py
  src/resource_manager/resource_manager.py
  src/state/config.py
  src/state/tls.py
  src/state/validation.py
Labels: Libraries: Out of sync, trivial

#46 Fix unit test workflow reference
  .github/workflows/test.yaml
Labels: Libraries: Out of sync, trivial

#28 ISD-1947 Implement secret resource manager and add HTTPS listener to gateway
  .github/workflows/integration_test.yaml
  src-docs/resource_definition.py.md
  src/charm.py
  src/resource_manager/gateway.py
  src/resource_manager/resource_manager.py
  src/resource_manager/secret.py
  src/state/base.py
  src/state/config.py
  src/state/gateway.py
  src/state/tls.py
  src/tls_relation.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_gateway.py
Labels: Libraries: Out of sync, complex

#50 ISD-2100 Refactor tls_relation module and charm state logic
  src/charm.py
  src/resource_manager/gateway.py
  src/resource_manager/permission.py
  src/resource_manager/resource_manager.py
  src/resource_manager/secret.py
  src/state/config.py
  src/state/exception.py
  src/state/gateway.py
  src/state/tls.py
  src/state/validation.py
  src/tls_relation.py
  tests/unit/conftest.py
  tests/unit/test_certificates_integration.py
Labels: Libraries: Out of sync, complex

#33 Implement ingress integration
  charmcraft.yaml
  lib/charms/traefik_k8s/v2/ingress.py
  src/charm.py
  src/exception.py
  src/resource_manager/http_route.py
  src/resource_manager/resource_manager.py
  src/resource_manager/service.py
  src/state/base.py
  src/state/http_route.py
  src/state/secret.py
  src/state/validation.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_gateway.py
Labels: Libraries: Out of sync, complex

#54 Update README
  .gitignore
  README.md
Labels: documentation, Libraries: Out of sync, trivial

#55 fix: rustc toolchain
  charmcraft.yaml
Labels: bug, Libraries: Out of sync, trivial

#18 Add unit and integration tests
  .github/workflows/integration_test.yaml
  pyproject.toml
  src/resource_manager/gateway.py
  tests/integration/conftest.py
  tests/integration/helper.py
  tests/integration/test_actions.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/test_action.py
  tests/unit/test_certificates_integration.py
  tests/unit/test_charm.py
  tests/unit/test_config.py
  tests/unit/test_gateway.py
  tests/unit/test_http_route.py
  tests/unit/test_ingress.py
  tests/unit/test_secret.py
Labels: Libraries: Out of sync, complex
