Repository canonical/gateway-api-integrator-operator, pull requests merged in 2024-08, with the labels that each got.

#58 update service and http route name to avoid collision
  src/resource_manager/http_route.py
  src/state/http_route.py
Labels: Libraries: Out of sync, trivial

#57 rername test
  tests/integration/test_actions.py
Labels: Libraries: Out of sync, trivial

#56 ISD-2020 Request cert when config changed
  src/charm.py
  src/resource_manager/gateway.py
  src/tls_relation.py
  tests/unit/test_certificates_integration.py
  tests/unit/test_charm.py
  tests/unit/test_gateway.py
  tests/unit/test_http_route.py
Labels: Libraries: Out of sync, complex

#60 update src docs
  src-docs/charm.py.md
  src-docs/exception.py.md
  src-docs/tls_relation.py.md
Labels: documentation, Libraries: OK, trivial

#62 Update discourse and matrix links
  docs/index.md
Labels: documentation, Libraries: OK, trivial
