Repository canonical/gateway-api-integrator-operator, pull requests merged in 2024-06, with the labels that each got.

#2 ISD-1900 initial charm with only tls relation implementation
  .github/workflows/integration_test.yaml
  .github/workflows/test.yaml
  actions.yaml
  charmcraft.yaml
  config.yaml
  lib/charms/tls_certificates_interface/v3/tls_certificates.py
  metadata.yaml
  requirements.txt
  src/charm.py
  src/exceptions.py
  src/gateway_definition.py
  src/tls_relation.py
  tests/integration/conftest.py
  tests/integration/requirements.txt
  tests/integration/test_certificates_integration.py
  tests/integration/test_charm.py
  tests/unit/conftest.py
  tests/unit/constants.py
  tests/unit/requirements.txt
  tests/unit/test_base.py
  tests/unit/test_certificates_integration.py
  tox.ini
Labels: Libraries: Out of sync, complex

#14 ISD-1900 add src-docs to minimal charm implementation
  src-docs/charm.py.md
  src-docs/exceptions.py.md
  src-docs/gateway_definition.py.md
  src-docs/tls_relation.py.md
Labels: Libraries: Out of sync, trivial

#13 use square brackets instead of .get() for relation data
  src/charm.py
Labels: Libraries: OK, trivial

#12 merge everything into charmcraft.yaml
  actions.yaml
  charmcraft.yaml
  config.yaml
  metadata.yaml
Labels: Libraries: OK, trivial

#3 ISD-1973 Implement gateway resource manager with HTTP listener
  .github/workflows/test.yaml
  charmcraft.yaml
  lib/charms/tls_certificates_interface/v3/tls_certificates.py
  requirements.txt
  src/charm.py
  src/exceptions.py
  src/gateway_definition.py
  src/resource_definition.py
  src/resource_manager/gateway.py
  src/resource_manager/resource_manager.py
  src/tls_relation.py
  tests/integration/conftest.py
  tests/integration/requirements.txt
  tests/integration/test_certificates_integration.py
  tests/unit/conftest.py
  tests/unit/constants.py
  tests/unit/requirements.txt
  tests/unit/test_certificates_integration.py
  tests/unit/test_gateway.py
  tox.ini
Labels: Libraries: Out of sync, complex

#25 use pydantic v2.6.4
  .github/workflows/test.yaml
  requirements.txt
Labels: Libraries: Out of sync, trivial

#16 ISD-1997 Add docs links to enable discourse-gatekeeper, add docs
  charmcraft.yaml
  docs/explanation/workflow.md
  docs/index.md
  docs/reference/actions.md
  docs/reference/create_gateway_resource.png
  docs/tutorial/getting-started.md
Labels: documentation, Libraries: Out of sync, trivial

#5 ISD-1986/ISD-1987 Refactor tls service and separate charm state
  src/charm.py
  src/resource_manager/gateway.py
  src/resource_manager/resource_manager.py
  src/state/config.py
  src/state/gateway.py
  src/state/tls.py
  src/state/validation.py
  src/tls_relation.py
  tests/unit/test_gateway.py
  tox.ini
Labels: Libraries: Out of sync, complex

#34 Update charmcraft to only run on noble
  .github/workflows/integration_test.yaml
  .github/workflows/test.yaml
  charmcraft.yaml
Labels: Libraries: Out of sync, trivial

#37 set charmcraft channel in wf
  .github/workflows/publish_charm.yaml
Labels: Libraries: Out of sync, trivial
